# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import test_generator_pb2 as test__generator__pb2


class TestGeneratorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSentence = channel.unary_unary(
                '/TestGenerator/GetSentence',
                request_serializer=test__generator__pb2.Word.SerializeToString,
                response_deserializer=test__generator__pb2.Sentence.FromString,
                )


class TestGeneratorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSentence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestGeneratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSentence': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSentence,
                    request_deserializer=test__generator__pb2.Word.FromString,
                    response_serializer=test__generator__pb2.Sentence.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TestGenerator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TestGenerator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSentence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TestGenerator/GetSentence',
            test__generator__pb2.Word.SerializeToString,
            test__generator__pb2.Sentence.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
